### ISSUE TITLE
Interesting  project

### ISSUE THREAD

**Issue by drasko** [status-im/nimbus#1]
Very interesting development going on here. Kudos.

Does the project have any IRC channel (Slack, Gitter, ...) for development collaboration?

**Comment by yglukhov** [comment]
Hey, thanks! There's a https://chat.status.im . Though I don't suppose there's a proper chatroom for nimbus. Maybe we should set it up 🤔

**Comment by arnetheduck** [comment]
Hi, join us in one of the status community chats! 

https://chat.status.im/#/room/#dev-status:status.im
https://chat.status.im/#/room/#nimbus:status.im
