### ISSUE TITLE
Implement a test runner for the standard ETH blockchain/state validation tests

### ISSUE THREAD

**Issue by zah** [status-im/nimbus#113]
The test cases are located here:
https://github.com/ethereum/tests/tree/develop/BlockchainTests
https://github.com/ethereum/tests/tree/develop/GeneralStateTests

... and described here:
https://ethereum-tests.readthedocs.io/en/latest/test_types/blockchain_tests.html
https://ethereum-tests.readthedocs.io/en/latest/test_types/state_tests.html

We need to implement a simple test runner similar to the existing one in `test_vm_json.nim`. As these tests are significantly larger in size, it will probably be better if add the [test suite repo](https://github.com/ethereum/tests) as a git submodule (the CI scripts may have to be modified to fetch all submodules).

Please consider that in the future, these tests will be executable over the JSON-RPC interface using [retesteth](https://github.com/ethereum/retesteth). The internal APIs can be structured to simplify the implementation of the JSON-RPC procs described here:

https://github.com/ethereum/interfaces/issues/4
https://github.com/ethereum/retesteth/issues/5

**Comment by coffeepots** [comment]
Can this be closed now?

**Comment by zah** [comment]
Well, let's change the closing criteria to "pass all state validation tests"

The test runner has already been implemented here:
https://github.com/status-im/nimbus/blob/master/tests/test_generalstate_json.nim

But a large number of tests are still disabled here:
https://github.com/status-im/nimbus/blob/master/tests/test_generalstate_failing.nim

For newcomers, we've written some helpful notes on debugging test failures in general:
https://github.com/status-im/nimbus/wiki/Understanding-and-debugging-Nimbus-EVM-JSON-tests

I think we'll soon need to update the notes after the [`debug_traceTransaction`](https://github.com/status-im/nimbus/issues/171
) implementation is ready and we gain some compatibility with the Remix debugger.

**Comment by tersec** [comment]
It's getting pretty close now, no?

**Comment by jangko** [comment]
only two failed GST left

**Comment by jangko** [comment]
fixed by #459, closing
