### ISSUE TITLE
[Info] Contract address collision

### ISSUE THREAD

**Issue by mratsim** [status-im/nimbus#133]
cc @coffeepots 

So that this is not lost within our sea of discussions: https://github.com/status-im/nimbus/blob/e1bc482f398db393b6f0674fdc349d4970808807/nimbus/vm/interpreter/opcodes_impl.nim#L553-L560

EIP-684

![2018-09-04_11-50-29](https://user-images.githubusercontent.com/22738317/45024342-1236b600-b039-11e8-957d-2054d495d4f0.png)

![2018-09-04_11-50-50](https://user-images.githubusercontent.com/22738317/45024350-1531a680-b039-11e8-9447-ca08e7f3d103.png)

**Comment by coffeepots** [comment]
The account nonce is now touched on contract address creation, so even if the new address ends up as a collision, the nonce gets incremented.
