### ISSUE TITLE
first fruit of debugging tool, block 49018 statediff result

### ISSUE THREAD

**Issue by jangko** [status-im/nimbus#188]
```json
{
  "before": [
    {
      "name": "contract",
      "address": "630ea66c8c5dc205d45a978573fa86df5af1fe7a",                  
      "nonce": "0000000000000000",
      "balance": "0",
      "codeHash": "",
      "storage": {}
    },
    {
      "name": "sender",
      "address": "3d0768da09ce77d25e2d998e6a7b6ed4b9116c2d",
      "nonce": "000000000000000A",
      "balance": "43f0cf1107e922ce",
      "codeHash": "",
      "storage": {}
    },
    {
      "name": "miner",
      "address": "bb7b8287f3f0a933474a79eae42cbca977791171",
      "nonce": "0000000000000003",
      "balance": "47d269fc4069450d050",
      "codeHash": "",
      "storage": {}
    }
  ],
  "after": [
    {
      "name": "contract",
      "address": "630ea66c8c5dc205d45a978573fa86df5af1fe7a",
      "nonce": "0000000000000000",
      "balance": "0",
      "codeHash": "",
      "storage": {}  //// HERE IS THE PROBLEM
    },
    {
      "name": "sender",
      "address": "3d0768da09ce77d25e2d998e6a7b6ed4b9116c2d",
      "nonce": "000000000000000B",
      "balance": "43d6743654e7182e",
      "codeHash": "",
      "storage": {}
    },
    {
      "name": "miner",
      "address": "bb7b8287f3f0a933474a79eae42cbca977791171",
      "nonce": "0000000000000003",
      "balance": "47d6c1db0638c46daf0",
      "codeHash": "",
      "storage": {}
    }
  ]
}

//// IT SHOULD BE LIKE THIS
{
  "name": "contract",
  "address": "630ea66c8c5dc205d45a978573fa86df5af1fe7a",
  "nonce": "0000000000000000",
  "balance": "0",
  "codeHash": "",
  "storage": {
    "b10e2d527612073b26eecdfd717e6a320cf44b4afac2b0732d9fcbe2b7fa0cf6": "48656c6c6f20576f726c64210000000000000000000000000000000000000000",
    "0000000000000000000000000000000000000000000000000000000000000001": "000000000000000000000000000000000000000000000000000000000000000c",
    "0000000000000000000000000000000000000000000000000000000000000000": "0000000000000000000000003d0768da09ce77d25e2d998e6a7b6ed4b9116c2d"
  }
}
```

the storage appear at op code trace, but somehow it vanish after transaction execution.
when I try manually insert storage to that address, the block stateRoot now match expected result, problem confirmed.

that problematic account storageRoot seems not updated, very strange. I could not locate the bug in the code. uncommitted memory layer db?

**Comment by zah** [comment]
An uncommitted memory layer sounds like a likely culprit indeed. Perhaps, there is an inappropriate exception being triggered somewhere before the call/transaction execution is complete.

**Comment by jangko** [comment]
although I've located the bug, my fix is not entirely correct. there should be only one state trie. have more than one state trie lying around only invites bug.

**Comment by zah** [comment]
I think the solution here is to create a new persistent mapping in the back-end database resolving contract hashes to their corresponding contract codes. You would do this by introducing a new `DBKeyKind` value in `storage_types.nim` and function such as `contractHashKey` that creates a database key. You would write the key-value pair directly to the underlying `trie.db` backing the `AccountStateDB`.

The fancy `JournalDB` is used in py-evm to solve the problem of rolling back blocks that were thrown away after a new alternative chain is selected (due to better fork choice score). We can address this problem later.
