### ISSUE TITLE
GC safety of Nimbus-related projects

### ISSUE THREAD

**Issue by stefantalpalaru** [status-im/nimbus#209]
Projects we're able to use with `--threads:on` (guaranteed by enabling it in their test suite):

- [x] cheatfate/nimcrypto - https://github.com/cheatfate/nimcrypto/commit/eb151ac3d0f1d46641c85b5e725da293ff72878a
- [x] jangko/snappy - https://github.com/jangko/snappy/pull/2
- [x] status-im/nim-asyncdispatch2 - https://github.com/status-im/nim-asyncdispatch2/pull/19
- [x] status-im/nim-bncurve - https://github.com/status-im/nim-bncurve/pull/4
- [x] status-im/nim-byteutils - https://github.com/status-im/nim-byteutils/pull/5
- [x] status-im/nim-chronicles - https://github.com/status-im/nim-chronicles/pull/42
- [x] status-im/nim-eth-bloom - https://github.com/status-im/nim-eth-bloom/pull/6
- [x] status-im/nim-eth-common - https://github.com/status-im/nim-eth-common/pull/25
- [x] status-im/nim-eth-keyfile - https://github.com/status-im/nim-eth-keyfile/pull/1
- [x] status-im/nim-eth-keys - https://github.com/status-im/nim-eth-keys/pull/17
- [x] status-im/nim-eth-p2p - https://github.com/status-im/nim-eth-p2p/issues/60
- [x] status-im/nim-eth-trie - https://github.com/status-im/nim-eth-trie/pull/32
- [x] status-im/nim-faststreams - https://github.com/status-im/nim-faststreams/pull/1
- [x] status-im/nim-http-utils - https://github.com/status-im/nim-http-utils/pull/3
- [x] status-im/nim-json-rpc - https://github.com/status-im/nim-json-rpc/pull/47
- [x] status-im/nim-json-serialization - https://github.com/status-im/nim-json-serialization/pull/1
- [x] status-im/nim-ranges - https://github.com/status-im/nim-ranges/pull/35
- [x] status-im/nim-rlp - https://github.com/status-im/nim-rlp/pull/23
- [x] status-im/nim-rocksdb - https://github.com/status-im/nim-rocksdb/pull/17
- [x] status-im/nim-secp256k1 - https://github.com/status-im/nim-secp256k1/pull/14
- [ ] status-im/nim-serialization - no test suite
- [ ] status-im/nim-std-shims - no test suite
- [x] status-im/nim-stint - https://github.com/status-im/nim-stint/pull/74
- [ ] zah/nim-package-visible-types - no test suite
- [x] status-im/nimbus - https://github.com/status-im/nimbus/pull/213 https://github.com/status-im/nim-rlp/pull/24 https://github.com/status-im/nim-eth-trie/pull/34 https://github.com/status-im/nim-eth-common/pull/26 https://github.com/status-im/nim-eth-p2p/pull/63 https://github.com/status-im/nimbus/pull/215

**Comment by jangko** [comment]
jangko/snappy#2

**Comment by stefantalpalaru** [comment]
Thanks. Added to the list.

**Comment by stefantalpalaru** [comment]
There's a stdlib bug on Windows that prevents threading there: https://github.com/nim-lang/Nim/issues/8294#issuecomment-454556051

**Comment by stefantalpalaru** [comment]
Goal achieved, but we might want to keep the issue open to track those 3 projects with no test suites.
