### ISSUE TITLE
SIGSEGV: Illegal storage access. (Attempt to read from nil?)

### ISSUE THREAD

**Issue by Swader** [status-im/nimbus#210]
#198 is back in the new build.

```bash
Bruno@LAPTOP-LL043296 MINGW64 ~/repos/nimbus (build)                             
$ ./build/nimbus.exe > log.txt                                                   
Traceback (most recent call last)                                               
nimbus.nim(145)          nimbus                                                 
nimbus.nim(124)          process                                                 
asyncloop.nim(238)       poll                                                    
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

Nimbus' entire 2-minute run output here:
[log.txt](https://github.com/status-im/nimbus/files/2737324/log.txt)

---

Steps to reproduce:

- build `build` branch (#200) on Windows 10 x64 with new makefile build system
- run in Git Bash

**Comment by stefantalpalaru** [comment]
Looks like a bug in https://github.com/status-im/nim-asyncdispatch2

The callback's argument somehow is nil at calling time: https://github.com/status-im/nim-asyncdispatch2/blob/90f2a50dda7f084cfca1c64e402d484847514a07/asyncdispatch2/asyncloop.nim#L238

Maybe garbage collected?

**Comment by cheatfate** [comment]
Which version of `nim-asyncdispatch2` you have installed? If it `2.1.5`, please upgrade it to `2.1.6`.

**Comment by Swader** [comment]
Fixed, thank you.
