### ISSUE TITLE
Move rationale to GitHub

### ISSUE THREAD

**Issue by drasko** [status-im/nimbus#23]
Google docs link is not accessible, please move the rationale doc to GitHub.

**Comment by drasko** [comment]
Any news on this issue?

If you please share Google doc, I can post a PR with the doc.

**Comment by mratsim** [comment]
Hello @drasko, sorry for the late reply.

Docs are being moved from Google docs to [this file](https://github.com/status-im/nimbus/blob/165b1872a602bb5fba4c4cb4e0353ab3c1fd033b/Nimbus%20-%20An%20Ethereum%202.0%20Sharding%20Client_xt.md) by @alexm-status.

There is still some polishing/renaming to be done.

**Comment by drasko** [comment]
Thanks @mratsim and @alexm-status
