### ISSUE TITLE
test_all no longer being executed in CI

### ISSUE THREAD

**Issue by stefantalpalaru** [status-im/nimbus#239]
We can't have multiple "test()" invocations in "nimbus.nimble" because of how setCommand() works. When `test "test_rpc"` was added after `test "test_all"` it replaced it completely. You can see the result here: https://travis-ci.org/status-im/nimbus/jobs/496386459

I fixed this problem in the "submodules" branch by replacing setCommand() with exec(): https://github.com/status-im/nimbus/pull/231

GitHub's interface doesn't let me assign this issue to @jangko, so I'll use a mention instead. Ideally, we'd figure out why "test_all.nim" was crashing when "test_rpc" was included. In the mean time, not running "test_rpc" is better than not running "test_all".

**Comment by jangko** [comment]
aha, that's why the CI test pass so quickly.
I'll push emergency fix at my next PR
