### ISSUE TITLE
failed to build debug mode executables on windows

### ISSUE THREAD

**Issue by jangko** [status-im/nimbus#314]
it will fail to compile with error message like this(most of them come from eth/p2p):

```text
Error: ':anonymous' is not GC-safe as it calls 'setProperty'
```

I suspect this problem is triggered by recent changes in chronicles. 

when build release mode executables, the error will dissapear

**Comment by stefantalpalaru** [comment]
Which executables? All the tools are built in debug mode. Just the tests are in release mode.

**Comment by jangko** [comment]
`nimbus` and `test_generalstate_json`, and `test_vm_json`, perhaps others

**Comment by jangko** [comment]
oops, wrong branch of nim compiler, sorry.
