### ISSUE TITLE
Stack/MessageOptions not converting hex integers to Uint256

### ISSUE THREAD

**Issue by mratsim** [status-im/nimbus#32]
The message option type is not converting hex string to Uint256:

https://github.com/status-im/nimbus/blob/43797485e5c50d94fef5a4b9afba858632190896/src/vm/message.nim#L42-L48

This leads to several test failures
```Nim
vmTestsboolean.json
test_helpers.nim(48)     test_vm_json
computation.nim(278)     testFixture
computation.nim(272)     :anonymous
context.nim(27)          caller
stack.nim(67)            push
validation.nim(48)       validateStackItem

    Unhandled exception: Invalid stack item: expected 32 bytes, got 42: value is 0xcd1722f3947def4cf144679da39c4c32bdc35681
  [FAILED] tests/fixtures/VMTests/vmTests/boolean.json
vmTestssuicide.json
test_helpers.nim(48)     test_vm_json
computation.nim(278)     testFixture
computation.nim(272)     :anonymous
context.nim(27)          caller
stack.nim(67)            push
validation.nim(48)       validateStackItem

    Unhandled exception: Invalid stack item: expected 32 bytes, got 42: value is 0xcd1722f3947def4cf144679da39c4c32bdc35681
  [FAILED] tests/fixtures/VMTests/vmTests/suicide.json
vmTestsmktx.json
test_helpers.nim(48)     test_vm_json
computation.nim(278)     testFixture
computation.nim(272)     :anonymous
context.nim(27)          caller
stack.nim(67)            push
validation.nim(48)       validateStackItem

    Unhandled exception: Invalid stack item: expected 32 bytes, got 42: value is 0xcd1722f3947def4cf144679da39c4c32bdc35681
```
https://github.com/status-im/nimbus/blob/43797485e5c50d94fef5a4b9afba858632190896/tests/fixtures/VMTests/vmTests/boolean.json#L17-L26
I didn't find any mention of MessageOptions type in Py-EVM, Go-Ethereum, Parity codebases even in past commits besides [Go Protobuf](https://github.com/ethereum/go-ethereum/blob/master/vendor/github.com/golang/protobuf/protoc-gen-go/descriptor/descriptor.pb.go).

**Comment by alehander42** [comment]
MessageOptions was basically just a typed version of the optional py-evm args being passed to newMessage, it's not a meaningful type otherwise
