### ISSUE TITLE
go-checks error in makefile

### ISSUE THREAD

**Issue by jangko** [status-im/nimbus#374]
I got this error message from [travis-ci console log](https://travis-ci.org/status-im/nimbus/jobs/571847210): 

```bash
$ make go-checks
Minimum Go compiler version required: 1.12.0. Version available: 1.11.1. Aborting.
Makefile:187: recipe for target 'go-checks' failed
make: *** [go-checks] Error 1
```

**Comment by stefantalpalaru** [comment]
Solved for Travis. Removed from AppVeyor. Proposed solution for when we'll have CI tests depending on Go: use a `make` parameter to disable the version check.
