### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by Araq** [status-im/nimbus#389]
On my Windows 10, 64 bit machine, I got:

```
Building: Nim compiler
cp: cannot stat 'bin/nim': No such file or directory
mingw32-make.exe: *** [Makefile:198: vendor/Nim/bin/nim.exe] Error 1
```

**Comment by stefantalpalaru** [comment]
There's a specific Mingw-w64 and "Git for Windows" setup you need on Windows: https://github.com/status-im/nimbus#windows

Where exactly did you stray away from the path?

**Comment by stefantalpalaru** [comment]
Also, to see error messages, increase the verbosity level with `mingw32-make V=1 ...`

**Comment by Araq** [comment]
I don't want to replace my git because it already works fine. But never mind, I found a way to bypass 'make' and your build setup.
