### ISSUE TITLE
test failure with Nim-1.0.4 release candidate

### ISSUE THREAD

**Issue by stefantalpalaru** [status-im/nimbus#424]
Using the "nim1.0.4" branch:

```text
  [OK] tests/fixtures/newGeneralStateTests/stArgsZeroOneBalance/xorNonConst.json
subtest no: 7 failed
```

There's also a problem with marking that failure, because there's no [FAILED] label.

**Comment by jangko** [comment]
I get worse error messages:
```
nimcache/release/test_generalstate_json/utils.nim.c.o: In function `parseAddress__trh1CSgdG9bVndhQ0q3oWww':
C:/Users/Jangko/.nimble/pkgs/eth-1.0.0/eth/common/utils.nim:8: multiple definition of `parseAddress__trh1CSgdG9bVndhQ0q3oWww'
nimcache/release/test_generalstate_json/utils.nim.c.o:C:/Users/Jangko/.nimble/pkgs/eth-1.0.0/eth/common/utils.nim:8: first defined here
nimcache/release/test_generalstate_json/utils.nim.c.o: In function `toHex__3p6VYpmDb6FsTe2ZIUcuNQbyteutils':
C:/Users/Jangko/.nimble/pkgs/stew-0.1.0/stew/byteutils.nim:125: multiple definition of `dollar___Kaj5xasOxq8cJRx5ksLlmQ'
nimcache/release/test_generalstate_json/utils.nim.c.o:C:/Users/Jangko/.nimble/pkgs/stew-0.1.0/stew/byteutils.nim:125: first defined here
nimcache/release/test_generalstate_json/utils.nim.c.o: In function `eth_utilsInit000':
C:/Users/Jangko/.nimble/pkgs/eth-1.0.0/eth/common/utils.nim:12: multiple definition of `eth_utilsInit000'
nimcache/release/test_generalstate_json/utils.nim.c.o:C:/Users/Jangko/.nimble/pkgs/eth-1.0.0/eth/common/utils.nim:12: first defined here
nimcache/release/test_generalstate_json/hash.nim.c.o: In function `burnMem__WQXOjiuy7r6qJs6Q2oUAcgutils':
C:/Users/Jangko/.nimble/pkgs/nimcrypto-0.4.5/nimcrypto/utils.nim:217: undefined reference to `burnMem__haAOjkJjOuRy8ux9bV57dXw'
nimcache/release/test_generalstate_json/hash.nim.c.o: In function `burnMem__3kHY0BwnzMmCH3xJFhlgPAutils':
C:/Users/Jangko/.nimble/pkgs/nimcrypto-0.4.5/nimcrypto/utils.nim:217: undefined reference to `burnMem__haAOjkJjOuRy8ux9bV57dXw'
```

probably another wave of bugs like v1.0.0 😄

**Comment by stefantalpalaru** [comment]
Try deleting "nimcache" first.

**Comment by jangko** [comment]
> Try deleting "nimcache" first.

I have try it, still cannot works.

**Comment by stefantalpalaru** [comment]
You're holding it wrong. You should not be using Nimble packages from "C:/Users/Jangko/.nimble/pkgs".

You're supposed to:

```text
git pull
git checkout nim1.0.4
make -j4 update
rm -rf nimcache
make -j4
make test
```

**Comment by jangko** [comment]
well, I think the bug I encountered is Windows specific. I can compile and run the test on linux without 'make'.

**Comment by stefantalpalaru** [comment]
> I can compile and run the test on linux without 'make'.

What's your Nim commit hash?

**Comment by jangko** [comment]
I use nim devel branch on both windows and linux

**Comment by stefantalpalaru** [comment]
Then you're testing the wrong compiler revision in the wrong branch.

This is the branch from which new releases are made: https://github.com/nim-lang/Nim/tree/version-1-0

And this is the commit we should be testing: https://github.com/nim-lang/Nim/commit/4084ef19a37dea0adefb9a162704985630b22b0f

**Comment by jangko** [comment]
it does'nt matter now, I already fixed this issue, and will report the new nim compiler bug.

**Comment by jangko** [comment]
re cryptic error messages on windows, I have ID the culprit: nim-lang/Nim#12734

**Comment by stefantalpalaru** [comment]
Great, but it shouldn't affect the 1.0.4 release candidate I was testing, because narimiran says he didn't backport the broken devel commit to the release branch.
