### ISSUE TITLE
Create standalone Waku / Whisper cli node

### ISSUE THREAD

**Issue by kdeme** [status-im/nimbus#426]
Standalone node with following minimum functionality, options configurable through cli:
- Whisper full node
- Waku full node
- Connect to Status fleet
- Discv4: default off
- Bootnode (currently for discv4): default off
- Waku - Whisper bridge: default off
- Store enode keypair
- port settings

**Comment by jakubgs** [comment]
I care about ability to control these things:

* Listen port
* Exposed public IP and port
* Data storage location
* Configuration location

Nice to have:

* Exposing metrics
* Memory limits
* Logging formatting (or lack of)

**Comment by oskarth** [comment]
@kdeme What's the state of this?

**Comment by kdeme** [comment]
Getting there.
Think most important parts missing before closing this are:
- Exposed public IP and port
- Data storage location -> Should probably store the generated node key in a file

**Comment by jakubgs** [comment]
Is this done? Where can I find information about how such a node is run?

**Comment by kdeme** [comment]
https://github.com/status-im/nimbus/blob/master/waku/README.md

But the readme does not contain Docker information nor did I push an image yet to Docker Hub, so Perhaps I should reopen :)

**Comment by jakubgs** [comment]
Give me your docker hub ID and I'll add you to `statusteam` org.
