### ISSUE TITLE
Implement Turboproofs

### ISSUE THREAD

**Issue by zah** [status-im/nimbus#468]
Nimbus should become a highly efficient Eth1 [stateless client](https://ethresear.ch/t/the-stateless-client-concept/172). To execute a block, a stateless client needs to obtain only a small portion of the state that is being referenced by the transactions in the block. The needed data can be downloaded on demand and its integrity can be verified through [merkle proofs](https://blog.ethereum.org/2015/11/15/merkling-in-ethereum/). We call this data "the witness" for the block. 

The [Turboproofs scheme](https://medium.com/@gballet/turboproofs-light-clients-and-saving-private-eth1-487aaa9b386) is an efficient method for compressing the block witness that was proposed by Alexey Akhunov. Existing implementations exist in [Rust](https://github.com/gballet/multiproof-rs) and [TypeScript](https://github.com/ewasm/biturbo/blob/master/src/multiproof.ts).

Goals of this bounty:

* [ ] Implement a module with low-level routines for working with turbo-proofs.
* [ ] Collect test vectors from existing implementations and implement a test suite.
* [ ] Add a routine that can generate a turbo-proof by [executing a block](https://github.com/status-im/nimbus/blob/master/nimbus/tracer.nim#L192) and keeping track of the referenced state trie data. 
* [ ] Add a routine that can populate a trie database (e.g. created with [`newMemoryDB`](https://github.com/status-im/nim-eth/blob/cca931d0b59edeb7cbe6d9e3be37b794cf2e4a16/eth/trie/db.nim#L124)) with the contents of a turbo-proof.

**Comment by zah** [comment]
A new specification for the block witnesses is being published here:
https://github.com/ethereum/stateless-ethereum-specs/pull/1/files

**Comment by zah** [comment]
@jangko, my understanding is that we already have everything needed to close this?

**Comment by jangko** [comment]
that's right, we can close this one.
